[versions]
jna = "5.18.1"
junit-jupiter = "5.10.2"
junit-platform = "1.10.2"
jreleaser = "1.22.0"

[libraries]
jna-platform = { module = "net.java.dev.jna:jna-platform", version.ref = "jna" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }

[plugins]
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }
